// <auto-generated />
using System;
using LegislacionAPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegislacionAPP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250906023410_AddDataProtectionKeys")]
    partial class AddDataProtectionKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.AmbitoAplicacion", b =>
                {
                    b.Property<int>("id_ambito_aplicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ambito_aplicacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_ambito_aplicacion"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("id_ambito_aplicacion");

                    b.ToTable("AmbitoAplicacion");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CCMICategoria", b =>
                {
                    b.Property<int>("id_ccmi_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ccmi_categoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_ccmi_categoria"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre");

                    b.Property<int>("orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<decimal>("peso_categoria")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("peso_categoria");

                    b.HasKey("id_ccmi_categoria");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("CCMICategoria");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CMMIEvaluacion", b =>
                {
                    b.Property<int>("id_evaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evaluacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_evaluacion"));

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime?>("fecha_cierre")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("id_empresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("id_usuario_auditor")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_auditor");

                    b.Property<byte?>("nivel_madurez")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("nivel_madurez");

                    b.Property<string>("observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("puntaje_global")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("puntaje_global");

                    b.HasKey("id_evaluacion");

                    b.HasIndex("id_empresa");

                    b.HasIndex("id_estado");

                    b.HasIndex("id_usuario_auditor");

                    b.ToTable("CMMIEvaluacion");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CMMIPregunta", b =>
                {
                    b.Property<int>("id_cmmi_pregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cmmi_pregunta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_cmmi_pregunta"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("codigo")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("codigo");

                    b.Property<bool>("es_critica")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_critica");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("id_ccmi_categoria")
                        .HasColumnType("int")
                        .HasColumnName("id_ccmi_categoria");

                    b.Property<int>("orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<decimal>("peso_pregunta")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("peso_pregunta");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("texto");

                    b.HasKey("id_cmmi_pregunta");

                    b.HasIndex("id_ccmi_categoria");

                    b.ToTable("CMMIPregunta");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CMMIRespuesta", b =>
                {
                    b.Property<int>("id_respuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_respuesta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_respuesta"));

                    b.Property<string>("evidencia_url")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("evidencia_url");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("id_ccmi_pregunta")
                        .HasColumnType("int")
                        .HasColumnName("id_ccmi_pregunta");

                    b.Property<int>("id_evaluacion")
                        .HasColumnType("int")
                        .HasColumnName("id_evaluacion");

                    b.Property<string>("observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("nota");

                    b.Property<byte>("valor")
                        .HasPrecision(5, 2)
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("valor");

                    b.HasKey("id_respuesta");

                    b.HasIndex("id_ccmi_pregunta");

                    b.HasIndex("id_evaluacion");

                    b.ToTable("CMMIRespuesta");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CicloAuditoria", b =>
                {
                    b.Property<int>("id_ciclo_auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ciclo_auditoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_ciclo_auditoria"));

                    b.Property<int>("articulos_aprobados")
                        .HasColumnType("int")
                        .HasColumnName("total_aprobados");

                    b.Property<int>("articulos_totales")
                        .HasColumnType("int")
                        .HasColumnName("total_segmentos");

                    b.Property<DateTime?>("fecha_cierre")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("id_legislacion")
                        .HasColumnType("int")
                        .HasColumnName("id_legislacion");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_aprobador");

                    b.Property<string>("motivo_cierre")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("motivo_cierre");

                    b.Property<int>("nivel_cmmi")
                        .HasColumnType("int")
                        .HasColumnName("nivel_cmmi");

                    b.Property<decimal?>("porcentaje_aprobado")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("porcentaje_aprobado");

                    b.Property<string>("resumen")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("resumen");

                    b.HasKey("id_ciclo_auditoria");

                    b.HasIndex("id_estado");

                    b.HasIndex("id_legislacion");

                    b.HasIndex("id_usuario");

                    b.ToTable("CicloAuditoria");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Empresa", b =>
                {
                    b.Property<int>("id_empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_empresa"));

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("id_pais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<int>("id_sector")
                        .HasColumnType("int")
                        .HasColumnName("id_sector");

                    b.Property<string>("logo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo");

                    b.Property<string>("nit")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("representante")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("representante");

                    b.HasKey("id_empresa");

                    b.HasIndex("id_estado");

                    b.HasIndex("id_pais");

                    b.HasIndex("id_sector");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Estado", b =>
                {
                    b.Property<int>("id_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_estado"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("color_hex")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color_hex");

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("id_estado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.EvaluacionSegmento", b =>
                {
                    b.Property<int>("id_evaluacion_segmento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evaluacion_segmento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_evaluacion_segmento"));

                    b.Property<string>("comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fecha_evaluacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<int>("id_auditor")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_auditor");

                    b.Property<int>("id_ciclo_auditoria")
                        .HasColumnType("int")
                        .HasColumnName("id_ciclo_auditoria");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("id_segmento_legislacion")
                        .HasColumnType("int")
                        .HasColumnName("id_segmento_legislacion");

                    b.HasKey("id_evaluacion_segmento");

                    b.HasIndex("id_auditor");

                    b.HasIndex("id_ciclo_auditoria");

                    b.HasIndex("id_estado");

                    b.HasIndex("id_segmento_legislacion");

                    b.ToTable("EvaluacionSegmento");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Evidencia", b =>
                {
                    b.Property<int>("id_evidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evidencia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_evidencia"));

                    b.Property<string>("comentario_opcional")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("comentario_opcional");

                    b.Property<string>("contenido_url")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("archivo_url");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fecha_subida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_subida");

                    b.Property<int>("id_evaluacion_segmento")
                        .HasColumnType("int")
                        .HasColumnName("id_evaluacion_segmento");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("nombre_archivo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_original");

                    b.Property<string>("sha256")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("sha256");

                    b.Property<int?>("tamano_bytes")
                        .HasColumnType("int")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("tipo_documento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("id_evidencia");

                    b.HasIndex("id_evaluacion_segmento");

                    b.HasIndex("id_usuario");

                    b.ToTable("Evidencia");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Legislacion", b =>
                {
                    b.Property<int>("id_legislacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_legislacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_legislacion"));

                    b.Property<string>("alias")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("alias");

                    b.Property<string>("codigo_interno")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_interno");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("fecha_vigencia")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_vigencia");

                    b.Property<int>("id_ambito_aplicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_ambito_aplicacion");

                    b.Property<int>("id_empresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("id_pais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_creador");

                    b.Property<string>("pdf_url")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("archivo_pdf_url");

                    b.Property<string>("subtitulo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("subtitulo");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("id_legislacion");

                    b.HasIndex("id_ambito_aplicacion");

                    b.HasIndex("id_empresa");

                    b.HasIndex("id_estado");

                    b.HasIndex("id_pais");

                    b.ToTable("Legislacion");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Pais", b =>
                {
                    b.Property<int>("id_pais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_pais"));

                    b.Property<string>("codigo_iso")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("codigo_iso");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id_pais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Rol", b =>
                {
                    b.Property<int>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_rol"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre");

                    b.HasKey("id_rol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Sector", b =>
                {
                    b.Property<int>("id_sector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sector");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_sector"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id_sector");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.SegmentoLegislacion", b =>
                {
                    b.Property<int>("id_segmento_legislacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_segmento_legislacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_segmento_legislacion"));

                    b.Property<string>("contenido")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("contenido");

                    b.Property<byte[]>("contenido_bin")
                        .HasColumnType("longblob")
                        .HasColumnName("contenido_bin");

                    b.Property<string>("contenido_url")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("contenido_url");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("id_legislacion")
                        .HasColumnType("int")
                        .HasColumnName("id_legislacion");

                    b.Property<int?>("id_segmento_padre")
                        .HasColumnType("int")
                        .HasColumnName("id_segmento_padre");

                    b.Property<int>("id_tipo_elemento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_elemento");

                    b.Property<string>("observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("observaciones");

                    b.Property<int>("orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<string>("tituloSegmento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tituloSegmento");

                    b.HasKey("id_segmento_legislacion");

                    b.HasIndex("id_legislacion");

                    b.HasIndex("id_segmento_padre");

                    b.HasIndex("id_tipo_elemento");

                    b.ToTable("SegmentoLegislacion");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.TipoElemento", b =>
                {
                    b.Property<int>("id_tipo_elemento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_elemento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_tipo_elemento"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("id_tipo_elemento");

                    b.ToTable("TipoElemento");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("contrasena_hash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("id_pais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<int>("id_rol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_estado");

                    b.HasIndex("id_pais");

                    b.HasIndex("id_rol");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.UsuarioEmpresa", b =>
                {
                    b.Property<int>("id_usuario_empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_empresa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_usuario_empresa"));

                    b.Property<DateTime>("fecha_asignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_asignacion");

                    b.Property<int>("id_empresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("id_rol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("id_usuario_empresa");

                    b.HasIndex("id_empresa");

                    b.HasIndex("id_rol");

                    b.HasIndex("id_usuario");

                    b.ToTable("UsuarioEmpresa");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CMMIEvaluacion", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("id_empresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Estado", "id_estadoNavigation")
                        .WithMany()
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Usuario", "id_UsuarioAuditorNavigation")
                        .WithMany()
                        .HasForeignKey("id_usuario_auditor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("id_UsuarioAuditorNavigation");

                    b.Navigation("id_estadoNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CMMIPregunta", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.CCMICategoria", "Categoria")
                        .WithMany("Preguntas")
                        .HasForeignKey("id_ccmi_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.CMMIEvaluacion", "id_ccmi_categoriaNavigation")
                        .WithMany()
                        .HasForeignKey("id_ccmi_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("id_ccmi_categoriaNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CMMIRespuesta", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.CMMIPregunta", "id_preguntaNavigation")
                        .WithMany()
                        .HasForeignKey("id_ccmi_pregunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.CMMIEvaluacion", "id_evaluacionNavigation")
                        .WithMany("Respuestas")
                        .HasForeignKey("id_evaluacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_evaluacionNavigation");

                    b.Navigation("id_preguntaNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CicloAuditoria", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.Estado", "id_estadoNavigation")
                        .WithMany("Ciclos")
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Legislacion", "id_legislacionNavigation")
                        .WithMany("Ciclos")
                        .HasForeignKey("id_legislacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Usuario", "id_usuarioNavigation")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_estadoNavigation");

                    b.Navigation("id_legislacionNavigation");

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Empresa", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.Estado", "id_estadoNavigation")
                        .WithMany("Empresas")
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Pais", "id_paisNavigation")
                        .WithMany("Empresas")
                        .HasForeignKey("id_pais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Sector", "id_sectorNavigation")
                        .WithMany("Empresas")
                        .HasForeignKey("id_sector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_estadoNavigation");

                    b.Navigation("id_paisNavigation");

                    b.Navigation("id_sectorNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.EvaluacionSegmento", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.Usuario", "id_auditorNavigation")
                        .WithMany()
                        .HasForeignKey("id_auditor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.CicloAuditoria", "id_ciclo_auditoriaNavigation")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("id_ciclo_auditoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Estado", "id_estadoNavigation")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.SegmentoLegislacion", "id_segmento_legislacionNavigation")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("id_segmento_legislacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_auditorNavigation");

                    b.Navigation("id_ciclo_auditoriaNavigation");

                    b.Navigation("id_estadoNavigation");

                    b.Navigation("id_segmento_legislacionNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Evidencia", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.EvaluacionSegmento", "id_evaluacion_segmentoNavigation")
                        .WithMany("Evidencias")
                        .HasForeignKey("id_evaluacion_segmento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Usuario", "id_usuario_Navigation")
                        .WithMany()
                        .HasForeignKey("id_usuario");

                    b.Navigation("id_evaluacion_segmentoNavigation");

                    b.Navigation("id_usuario_Navigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Legislacion", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.AmbitoAplicacion", "id_ambito_aplicacionNavigation")
                        .WithMany("Legislaciones")
                        .HasForeignKey("id_ambito_aplicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Empresa", "id_empresaNavigation")
                        .WithMany("Legislacions")
                        .HasForeignKey("id_empresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Estado", "id_estadoNavigation")
                        .WithMany("Legislaciones")
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Pais", "id_paisNavigation")
                        .WithMany()
                        .HasForeignKey("id_pais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_ambito_aplicacionNavigation");

                    b.Navigation("id_empresaNavigation");

                    b.Navigation("id_estadoNavigation");

                    b.Navigation("id_paisNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.SegmentoLegislacion", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.Legislacion", "id_legislacionNavigation")
                        .WithMany("Segmentos")
                        .HasForeignKey("id_legislacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.SegmentoLegislacion", "id_segmento_padreNavigation")
                        .WithMany("Hijos")
                        .HasForeignKey("id_segmento_padre");

                    b.HasOne("LegislacionAPP.Models.DBModels.TipoElemento", "id_tipo_elementoNavigation")
                        .WithMany("Segmentos")
                        .HasForeignKey("id_tipo_elemento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_legislacionNavigation");

                    b.Navigation("id_segmento_padreNavigation");

                    b.Navigation("id_tipo_elementoNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Usuario", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.Estado", "id_estadoNavigation")
                        .WithMany()
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Pais", "id_paisNavigation")
                        .WithMany()
                        .HasForeignKey("id_pais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Rol", "id_rolNavigation")
                        .WithMany()
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_estadoNavigation");

                    b.Navigation("id_paisNavigation");

                    b.Navigation("id_rolNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.UsuarioEmpresa", b =>
                {
                    b.HasOne("LegislacionAPP.Models.DBModels.Empresa", "id_empresaNavigation")
                        .WithMany("UsuarioEmpresas")
                        .HasForeignKey("id_empresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Rol", "id_rolNavigation")
                        .WithMany("UsuarioEmpresas")
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegislacionAPP.Models.DBModels.Usuario", "id_usuarioNavigation")
                        .WithMany("UsuarioEmpresas")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_empresaNavigation");

                    b.Navigation("id_rolNavigation");

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.AmbitoAplicacion", b =>
                {
                    b.Navigation("Legislaciones");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CCMICategoria", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CMMIEvaluacion", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.CicloAuditoria", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Empresa", b =>
                {
                    b.Navigation("Legislacions");

                    b.Navigation("UsuarioEmpresas");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Estado", b =>
                {
                    b.Navigation("Ciclos");

                    b.Navigation("Empresas");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Legislaciones");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.EvaluacionSegmento", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Legislacion", b =>
                {
                    b.Navigation("Ciclos");

                    b.Navigation("Segmentos");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Pais", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Rol", b =>
                {
                    b.Navigation("UsuarioEmpresas");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Sector", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.SegmentoLegislacion", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.TipoElemento", b =>
                {
                    b.Navigation("Segmentos");
                });

            modelBuilder.Entity("LegislacionAPP.Models.DBModels.Usuario", b =>
                {
                    b.Navigation("UsuarioEmpresas");
                });
#pragma warning restore 612, 618
        }
    }
}
